### ISSUE TITLE
Better group name required

### ISSUE THREAD

**Issue by spitchell** [FAC-Overflow/proceedings#1]
FAC Overflow is no longer an adequate name (in my view) for  a whole bunch of reasons that I probably don't need to list here.

We need a name that is appropriate to represent an independent organisation with commercial aspirations,  and which can grow into its own identifiable brand.

**Comment by spitchell** [comment]
**The Literal Approach**

* Co-operative Code
* Coding Co-operative
* ~~Coding Collective~~ taken/too generic/ungooglable 
* ~~Code Collective~~

**Comment by madeleinel** [comment]
* Coders Anonymous (although might make for copyright issues?)

**Comment by AntonioDaria** [comment]
how about something like Codev</>( as code developers and cooperative).

just an idea i like the word dev in it

**Comment by spitchell** [comment]
I want to change the org name to _Cooperative Code_ as a placeholder, just to get us away from FAC associations until we can do a proper rebrand. Thoughts?

**Comment by madeleinel** [comment]
I'm up for having a temporary name until we settle on something permanent; Cooperative Code (CC) works for me

**Comment by AntonioDaria** [comment]
Cooperative Code works fine as placeholder

**Comment by spitchell** [comment]
OK, I've gone ahead and changed the display name of the github org. Looks like a new org or some kind of URL transfer will be needed down the line. I'll go ahead and make a new gitter community, too.

**Comment by spitchell** [comment]
I'm closing this issue, the relevent aspects of the original wording having been addressed. There may well be cause to open new name-related issues in future.
